name: Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has been inactive for 60 days and will be closed in 7 days if no further activity occurs.'
          stale-pr-message: 'This PR has been inactive for 60 days and will be closed in 7 days if no further activity occurs.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'help wanted,good first issue,contributor-reward'
          exempt-pr-labels: 'help wanted'
