name: Welcome Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for opening your first issue!

            Check our [Contributing Guide](CONTRIBUTING.md) for more information.
          pr-message: |
            Thanks for your first pull request!

            Learn about our [OSS Contributors Program](https://kaizen.tools/oss) - earn free Pro tier with 3+ merged PRs!
